### PR TITLE
Curve arithmetic

### PR DESCRIPTION
**Pull request by ewynx**
Implementation of curve arithmetic: add, double, mixed_add and mul. 

Field & field64 and scalar & scalar64 respectively have been merged for more clarity. 

Note: forc `v0.37.1` is needed to run the tests.

### CODE REVIEW

**Review by Mikerah — CHANGES_REQUESTED** [review]
Overall, the repo needs to be cleaned up quite a bit. There are a lot of tests and utils related folders that should be consolidated into one place e.g `tests` or `src/utils`. Issues should be opened up to do this work. Further, there is some code that is currently being worked on that has crept into this branch that makes it such that it cannot be run.

**Comment by ewynx** [comment]
Improved README's and removed a non-existing link to file. Should be possible to run tests in `p256_tests` 🫡

**Review by Mikerah — CHANGES_REQUESTED** [review]
- Remove all warnings during building/compilation if possible. For example, there's a warning field.sw on line 18 with regards to not using screaming snake case. Other warnings that aren't yet possible to resolve should have an associated issue opened for them for us to keep track of.
-

**Comment by man2706kum** [comment]
The following changes has been done as per the PR review-
1. Addition of a new file modular_helper.sw which refractors sub_inner, add, mul_wide, ct_eq & conditional_select to use in field and scalar.
2. Name changed from "modulus" to "MODULUS_FE" for field and "MODULUS" to "MODULUS_SCALAR" for scalar for the screaming snake case warning.
3.  removed all possible warning except for "casting from u64 to u8" which is not possible to remove at the moment.
4. A different comment is there in sub_inner now therefore typo is no more present.

**Review by Mikerah — APPROVED** [review]

**Pull request merged**
